# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "814656d35249aa7b69877b65dc03a0a1"
name = "digiful"
handle = "digiful"
application_url = "https://accuracy-printed-isp-flower.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-d30a541f.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://accuracy-printed-isp-flower.trycloudflare.com/auth/callback",
  "https://accuracy-printed-isp-flower.trycloudflare.com/auth/shopify/callback",
  "https://accuracy-printed-isp-flower.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
