# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "814656d35249aa7b69877b65dc03a0a1"
name = "digiful"
handle = "digiful"
application_url = "https://bars-organized-expenditures-hockey.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-d30a541f.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,write_products,read_publications,write_publications,write_inventory"

[auth]
redirect_urls = [
  "https://bars-organized-expenditures-hockey.trycloudflare.com/auth/callback",
  "https://bars-organized-expenditures-hockey.trycloudflare.com/auth/shopify/callback",
  "https://bars-organized-expenditures-hockey.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

#  [[webhooks.subscriptions]]
#  topics = [ "app/scopes_update" ]
#  uri = "https://parameter-decisions-ventures-ppc.trycloudflare.com/webhooks/app/scopes_update"

#  [[webhooks.subscriptions]]
#  topics = [ "app/uninstalled" ]
#  uri = "https://parameter-decisions-ventures-ppc.trycloudflare.com/webhooks/app/uninstalled"

[pos]
embedded = false
